<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260826/blob/main/tibame20260923.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import urllib.request as req

url = "https://github.com/Elwing-Chou/tibame20260826/raw/refs/heads/main/total.csv"
req.urlretrieve(url, "total.csv")

('total.csv', <http.client.HTTPMessage at 0x7ae0bc7e10f0>)

In [3]:
import pandas as pd
df = pd.read_csv("total.csv", encoding="utf-8")
df

                    text    color  size  position   time     sn       userid
0                      簽  #A7FE39     1         0      0  30997     k9219059
1      2022.8.22第一個 耶～～😋  #FF02D3     2         0      2  30997  Amy20080403
2                      👌  #FFFFFF     1         0     10  30997      winolee
3             一集接一集停不下來～  #FFFFFF     1         0     35  30997  eggplant171
4           前面的，你每集都出現耶😂  #FFFFFF     1         0     37  30997  love3769846
...                  ...      ...   ...       ...    ...    ...          ...
36001              兩個大胸鬼  #FFFFFF     1         0  12939  30996       aaidjd
36002     龍顯蕙聲線真的很適合妖媚的鬼  #FFFFFF     1         0  13130  30996  eggplant171
36003               玟次郎？  #FDE53D     2         2  13855  30996      lpx1007
36004            戳爆他的泡泡！  #FFFFFF     1         0  13938  30996      LWT1109
36005    別把他弄醒了，睡著時比較可靠呀  #FFFFFF     1         0  13958  30996      gamefan

[36006 rows x 7 columns]

- pandas兩大操作
    - 過濾: 把不要的資料丟掉
        - 準備跟你資料筆數一樣多的True/False, []帶入你的DataFrame
    - 轉換: 把整行轉換成另外一種格式

In [7]:
fil = [True, False, False]
df.head(3)[fil]

  text    color  size  position  time     sn    userid
0    簽  #A7FE39     1         0     0  30997  k9219059

In [ ]:
# unique()/value_counts()
import os

dn = "analyse"
if not os.path.exists(dn):
    os.makedirs(dn)

uids = df["userid"].unique()
for uid in uids:
    #uid = uids[0]
    fil = df["userid"] == uid
    df[fil].to_csv(f"{dn}/{uid}.csv",
                   encoding="utf-8",
                   index=False)

In [ ]:
# linux指令: 壓縮整個資料夾
!zip -r /content/file.zip /content/analyse

- 前端(Local)
    - 秀出回應(網頁)
        - HTML: 內容(O)
        - CSS: 排版(O)
        - JavaScript程式: 動態(X)

- 後端(Server)
    - 收網址
    - 有一個程式來處理網址(Flask, Django, FastAPI...)
        - 查詢資料庫
        - 讀取檔案
    - 把回應(html/json...)送回去

- CSS語法: 找到html區塊並且加上排版
    - 找所有html名字
    - 為了那夠去區分我真的要的區塊, 我會在html區塊上加上一個特殊屬性
        - class="分類1 分類2"
    
    - 如果你需要的是獨一無二的標籤, 特殊屬性
        - id="獨一無二的"

```
a{
    background-color:red
}
```

```
.分類名字{
    規則
}

.js-thumbnail-img{
    border-radius:50%
}

```

```
#id名字{

}
```

In [27]:
import urllib.request as req
import bs4 as bs

url = "https://tabelog.com/tw/tokyo/rstLst/sweets/?SrtT=rt"
resp = req.urlopen(url)
content = resp.read()
html = bs.BeautifulSoup(content)
# html.find("a", {"class":"list-rst__rst-name-target"})
rs = html.find_all("div", {"class":"list-rst__body"})
for r in rs:
    name = r.find("a", {"class":"list-rst__rst-name-target"})
    area_genre = r.find("div", {"class":"list-rst__area-genre"})

    name_text = name.get_text()
    name_href = name["href"]
    area_genre_text = area_genre.get_text().strip()

    print(name_text)
    print(name_href)
    print(area_genre_text)
    print("-" * 30)

Bon.nu
https://tabelog.com/tw/tokyo/A1304/A130401/13184186/
參宮橋車站 356m / 法式料理, 牛排, 蛋糕
------------------------------
Yama
https://tabelog.com/tw/tokyo/A1316/A131602/13279936/
白金台車站 725m / 甜食
------------------------------
Okashiya Ucchi
https://tabelog.com/tw/tokyo/A1309/A130901/13238644/
北參道車站 250m / 蛋糕, 西式甜點
------------------------------
蒼菓
https://tabelog.com/tw/tokyo/A1307/A130703/13297330/
廣尾車站 702m / 甜食
------------------------------
ESPRIT C. KEI GINZA
https://tabelog.com/tw/tokyo/A1301/A130101/13296199/
銀座車站 332m / 法式料理, 甜食
------------------------------
GELATERIA ACQUOLINA
https://tabelog.com/tw/tokyo/A1317/A131701/13141364/
祐天寺車站 45m / 意式冰淇淋/冰淇淋, 軟冰淇淋
------------------------------
Patisserie Ryoko
https://tabelog.com/tw/tokyo/A1316/A131603/13137010/
高輪台車站 423m / 蛋糕, 泡芙, 西式甜點
------------------------------
a tes souhaits!
https://tabelog.com/tw/tokyo/A1320/A132001/13005853/
西荻窪車站 992m / 蛋糕, 甜食
------------------------------
AIGRE DOUCE
https://tabelog.com/tw/tokyo/A1305/A130502/13005641/
目白車站 562m / 蛋糕, 馬卡龍
------------------------------
Frederic Cassel 銀座三越店
https://tabelog.com/tw/tokyo/A1301/A130101/13116839/
銀座車站 176m / 蛋糕, 甜食, 巧克力
------------------------------
patisserie Paris S'eveille
https://tabelog.com/tw/tokyo/A1317/A131703/13005198/
自由丘車站 212m / 蛋糕, 咖啡店, 麵包
------------------------------
CHOCOLATIER PALET D’OR 東京
https://tabelog.com/tw/tokyo/A1302/A130201/13038473/
二重橋前車站 351m / 巧克力, 咖啡店, 蛋糕
------------------------------
Think
https://tabelog.com/tw/tokyo/A1311/A131105/13283557/
鶯谷車站 643m / 麵包, 西式甜點
------------------------------
VIRON 丸之內店
https://tabelog.com/tw/tokyo/A1302/A130201/13043904/
東京車站 320m / 麵包, 蛋糕, 咖啡店
------------------------------
Avranches Guesnay
https://tabelog.com/tw/tokyo/A1310/A131004/13186450/
春日車站 30m / 蛋糕, 巧克力
------------------------------
Boulangerie Sudo
https://tabelog.com/tw/tokyo/A1317/A131709/13098861/
松陰神社前車站 34m / 麵包, 咖啡店, 甜食
------------------------------
patisserie K.ViNCENT
https://tabelog.com/tw/tokyo/A1309/A130905/13035194/
飯田橋車站 408m / 蛋糕, 巧克力, 西式甜點
------------------------------
Usagiya
https://tabelog.com/tw/tokyo/A1311/A131101/13003599/
湯島車站 195m / 日式點心, 銅鑼燒
------------------------------
日本橋 長門
https://tabelog.com/tw/tokyo/A1302/A130202/13011481/
日本橋車站 292m / 日式點心
------------------------------
GAZTA
https://tabelog.com/tw/tokyo/A1316/A131602/13223261/
白金高輪車站 271m / 蛋糕
------------------------------